### ISSUE TITLE
How to get us cities from this?

### ISSUE THREAD

**Issue by nicopeck** [nicholidev/country-cities#5]
### Discussed in https://github.com/nicholidev/country-cities/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **nicholidev** January 12, 2023</sup>
Please ask anything if you have any questions</div>

**Comment by nicholidev** [comment]
You can get it easily

`import {cities} from "country-cities"`

`cities.getByCountry("US")`

**Comment by nicopeck** [comment]
Perfect. That is working
